server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  port: 8080
spring:
  session:
    store-type: jdbc # 또는 redis, mongodb 등
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Seoul
  application:
    name: timeto
  security:
    oauth2:
      client:
        registration:
          google:
            # redirect-uri: ${BASE_URL}/login/oauth2/code/google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PASSWORD}
            scope:
              - email
              - profile
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method